### ISSUE TITLE
Error in setting low resolutions

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/modal#1]
If the lowest order approximation is good enough for the resolution, the code throws an error.

Traceback (most recent call last):

  File "<ipython-input-5-743409b11df0>", line 20, in <module>
    maxN = 14)

  File "rus.py", line 93, in __init__
    self.compute_resolutions(tol) # This will fill up self.dps and self.pvs

  File "rus.py", line 171, in compute_resolutions
    supremumN = min(set(Ns) - set(range(max(Nvs) + 1)))

**Comment by bbbales2** [comment]
Fixed
